// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4wf9In0VgD7ga-qhjyr_dewyxAMXqa1k',
    appId: '1:482563736192:web:3db8e5e7728ec32b19dc65',
    messagingSenderId: '482563736192',
    projectId: 'chatapp-943c9',
    authDomain: 'chatapp-943c9.firebaseapp.com',
    databaseURL: 'https://chatapp-943c9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-943c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApo36eMsavS_wIOaWzUripLp4u9RNYiPE',
    appId: '1:482563736192:android:8ed8d3c5e7b2510e19dc65',
    messagingSenderId: '482563736192',
    projectId: 'chatapp-943c9',
    databaseURL: 'https://chatapp-943c9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-943c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiCrl45B6A3ywvdNkYhcuL5vBFPb-iJKo',
    appId: '1:482563736192:ios:e1356e1891f66a2419dc65',
    messagingSenderId: '482563736192',
    projectId: 'chatapp-943c9',
    databaseURL: 'https://chatapp-943c9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-943c9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiCrl45B6A3ywvdNkYhcuL5vBFPb-iJKo',
    appId: '1:482563736192:ios:e1356e1891f66a2419dc65',
    messagingSenderId: '482563736192',
    projectId: 'chatapp-943c9',
    databaseURL: 'https://chatapp-943c9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-943c9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4wf9In0VgD7ga-qhjyr_dewyxAMXqa1k',
    appId: '1:482563736192:web:09214a3916eccd3219dc65',
    messagingSenderId: '482563736192',
    projectId: 'chatapp-943c9',
    authDomain: 'chatapp-943c9.firebaseapp.com',
    databaseURL: 'https://chatapp-943c9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-943c9.firebasestorage.app',
  );

}